### PR TITLE
Read binary file using pkgutil.get_data

### PR DESCRIPTION
**Pull request by ljodal**
When running as a [zipapp][1] it's not possible to read package data
directly from the file system, as the zip file is not extracted. Using
[`pkgutil.get_data`][2] works, making the library compatible with being
installed in a zipapp.

One downside with this is that the entire file is ready into memory
instead of being parsed while on disk, but as the file is only 1.4 MB
this probably shouldn't be a big issue.

[1]: https://docs.python.org/3/library/zipapp.html
[2]: https://docs.python.org/3/library/pkgutil.html#pkgutil.get_data

### CODE REVIEW

**Comment by sethmlarson** [comment]
Thanks for the interest, I agree it'd be a good idea to use `pkgutil` or some other official means of resolving the path to the binary file. Perhaps we can look at [`pkgutil.get_data()`](https://github.com/python/cpython/blob/3.8/Lib/pkgutil.py#L597) and figure out how it resolves paths and then use that instead of loading everything into memory.

1.4 MB getting loaded into memory is a deal-breaker for smaller devices which this library would be used on. Also I have plans to make this library compatible with async I/O interfaces. :)

**Comment by ljodal** [comment]
Thanks for the quick feedback! I'll look into avoid reading the file into memory (or worst case maybe try to open the file first and then fall back to `pkgutils`)

No rush from my end though, turns out I needed the cryptography library which is partially written in C so I can't run as a zipapp anyway.

**Comment by f0ff886f** [comment]
I believe the right function to use is `importlib.resources.open_binary(package, resource)` in Python 3.7+ is what you want. It would be great to get this fixed as it will get hstspreload working PyOxidizer too :) @ljodal if you are unable to look at this I'll try to make some time for it.

There's some more examples and information in https://github.com/indygreg/PyOxidizer/issues/69

**Comment by sethmlarson** [comment]
@f0ff886f Maybe you could create a PR that bundles the package differently per version? I'd like to continue to support Python 3.6 for now but I totally agree that using `open_binary()` is the "right" thing to do.

**Comment by f0ff886f** [comment]
@sethmlarson done in #8

**Comment by sethmlarson** [comment]
Closing this in favor of #8. Thank you @ljodal and @f0ff886f! :heart:

**Pull request closed without merging**
